#!/bin/sh

set -e

_mirror="http://ftp.debian.org/debian"
_dist="stretch"

lb config noauto \
	--clean \
	--mode debian \
	--distribution "${_dist}" \
	--architectures amd64 \
	--binary-images iso-hybrid \
	--debian-installer false \
	--memtest memtest86+ \
	--linux-flavours "amd64" \
	--linux-packages "linux-image linux-headers" \
	--mirror-bootstrap "${_mirror}" \
	--mirror-binary "http://deb.debian.org/debian" \
	--archive-areas "main contrib non-free" \
	--apt-source-archives false \
	--security true \
	--source false \
	--firmware-chroot true \
	--bootappend-live 'boot=live components'" hostname=${_dist}-live "'toram=filesystem.squashfs console=ttyS0,115200n8 console=tty0 \"\$\{loopback\}\" \"\$\{kernelopts\}\"' \
	--bootappend-live-failsafe 'boot=live components'" hostname=${_dist}-live "'memtest noapic noapm nodma nomce nolapic nomodeset nosmp nosplash vga=normal console=ttyS0,115200n8 console=tty0 \"\$\{loopback\}\" \"\$\{kernelopts\}\"' \
	"${@}"

